from typing import Self

class RotationBuffer:
    def __init__(self, size: int) -> None: ...
    def put(self, val: float) -> None: ...
    def max(self) -> float: ...
    def reset(self) -> None: ...
    def __imul__(self, val: float) -> Self: ...
